name: NPM Install
description: Install npm packages
runs:
  using: composite
  steps:
    - name: restore_cache
      uses: actions/cache@v4
      with:
        key: node-${{ hashFiles('package-lock.json') }}
        path: node_modules
        restore-keys: |-
          node-${{ hashFiles('package-lock.json') }}
          node-
    - name: Install npm packages
      run: npm ci
      shell: bash
    - name: save_cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: node-${{ hashFiles('package-lock.json') }}
