name: DSmartTrader Test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Install Dependencies
        uses: "./.github/actions/npm_install"

      - name: Build
        uses: "./.github/actions/build"
        with:
          target: production

      - name: Run Tests
        run: npm run test
