name: DSmartTrader Test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: "./.github/actions/setup_node"

      - name: Install Dependencies
        uses: "./.github/actions/npm_install"

      - name: Build
        uses: "./.github/actions/build"
        with:
          target: production

      - name: Run Tests
        run: npm run test
