name: DSmartTrader Test
on:
  pull_request:
    branches:
      - master
jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Setup Node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: 18.x
      - name: Install dependencies
        uses: "./.github/actions/npm_install"
      - name: Build
        uses: "./.github/actions/build"
        with:
          target: production
      - name: "Run Tests"
        run: npm run test
